### ISSUE TITLE
Lucid model's not being serialized in response

### ISSUE THREAD

**Issue by imikodanic** [Treblle/treblle-adonisjs#2]
When I fetch some model using lucid it isn't serialized when shown in Treblle Request, but in Postman response everything looks fine.
<img width="1046" alt="Screenshot 2023-06-08 at 11 09 48" src="https://github.com/Treblle/treblle-adonisjs/assets/40581978/704599dc-aafc-4a57-b421-ec040f73c12a">

**Comment by DominusKelvin** [comment]
Thanks for the details on this issue @Mikodanic-I I'll take a look and start working on it.

**Comment by DominusKelvin** [comment]
I've been able to reproduce this @Mikodanic-I 

In my case, this action

![CleanShot 2023-06-09 at 15 38 55@2x](https://github.com/Treblle/treblle-adonisjs/assets/24433274/7a70f04b-e136-4ca5-8751-777e00d3dede)


Produces this response in Treblle dashboard

![CleanShot 2023-06-09 at 15 38 55@2x](https://github.com/Treblle/treblle-adonisjs/assets/24433274/ccba96fd-8eb3-4ca7-b638-c91b73e4657c)
